-- AlterTable
ALTER TABLE "DataResponden" ALTER COLUMN "hitung1" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "hitung2" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "hitung3" SET DATA TYPE DOUBLE PRECISION;
